default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: "<%= ENV.fetch('DATABASE_HOST', 'postgres') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', '5432') %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'meideiteam') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'meideiteam') %>"
  database: star_padel_development

test:
  <<: *default
  host: "<%= ENV.fetch('DATABASE_HOST', 'postgres') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', '5432') %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'meideiteam') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'meideiteam') %>"
  database: star_padel_test

production:
  <<: *default
  database: <%= ENV['RDS_DATABASE'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  post: 5432