default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: "<%= ENV.fetch('DATABASE_HOST', 'postgres') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', '5432') %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'meideiteam') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'meideiteam') %>"
  database: star_padel_development

test:
  <<: *default
  host: "<%= ENV.fetch('DATABASE_HOST', 'postgres') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', '5432') %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'meideiteam') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'meideiteam') %>"
  database: star_padel_test

production:
  <<: *default
  database: star_padel_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>