---
:concurrency: 5
production:
  :concurrency: 3
:queues:
  - exports
  - default
# :schedule:
#   health_test:
#     cron: "* * * * * *" # Execute every minute (for testing)
#     class: HealthJob
#     description: "Health test to check if APP is working"
