---
:concurrency: 5
production:
  :concurrency: 3
:queues:
  - exports
  - default
# :schedule:
#   health_test:
#     cron: "0 */25 * * * *"
#     class: HealthJob
#     description: "Health test to check if APP is working"
